// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: proto/cipher/v1/cipher.proto

package cipher

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EncryptRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The value to protect. Never logged.
	Plaintext []byte `protobuf:"bytes,1,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	// Bound into the ciphertext as additional authenticated data. A value sealed for one
	// purpose therefore cannot be decrypted as another, even by a caller holding both.
	// Convention: "model-api-key", "ssh-private-key", and so on.
	Context       string `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptRequest) Reset() {
	*x = EncryptRequest{}
	mi := &file_proto_cipher_v1_cipher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptRequest) ProtoMessage() {}

func (x *EncryptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cipher_v1_cipher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptRequest.ProtoReflect.Descriptor instead.
func (*EncryptRequest) Descriptor() ([]byte, []int) {
	return file_proto_cipher_v1_cipher_proto_rawDescGZIP(), []int{0}
}

func (x *EncryptRequest) GetPlaintext() []byte {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

func (x *EncryptRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

type EncryptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ciphertext    []byte                 `protobuf:"bytes,1,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	KeyId         string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptResponse) Reset() {
	*x = EncryptResponse{}
	mi := &file_proto_cipher_v1_cipher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptResponse) ProtoMessage() {}

func (x *EncryptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cipher_v1_cipher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptResponse.ProtoReflect.Descriptor instead.
func (*EncryptResponse) Descriptor() ([]byte, []int) {
	return file_proto_cipher_v1_cipher_proto_rawDescGZIP(), []int{1}
}

func (x *EncryptResponse) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *EncryptResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

type DecryptRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Ciphertext []byte                 `protobuf:"bytes,1,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	// Must match the context the value was encrypted with, or decryption fails.
	Context string `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	// Which key opens it. Empty means the active one.
	KeyId         string `protobuf:"bytes,3,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptRequest) Reset() {
	*x = DecryptRequest{}
	mi := &file_proto_cipher_v1_cipher_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptRequest) ProtoMessage() {}

func (x *DecryptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cipher_v1_cipher_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptRequest.ProtoReflect.Descriptor instead.
func (*DecryptRequest) Descriptor() ([]byte, []int) {
	return file_proto_cipher_v1_cipher_proto_rawDescGZIP(), []int{2}
}

func (x *DecryptRequest) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *DecryptRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *DecryptRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

type DecryptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plaintext     []byte                 `protobuf:"bytes,1,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptResponse) Reset() {
	*x = DecryptResponse{}
	mi := &file_proto_cipher_v1_cipher_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptResponse) ProtoMessage() {}

func (x *DecryptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cipher_v1_cipher_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptResponse.ProtoReflect.Descriptor instead.
func (*DecryptResponse) Descriptor() ([]byte, []int) {
	return file_proto_cipher_v1_cipher_proto_rawDescGZIP(), []int{3}
}

func (x *DecryptResponse) GetPlaintext() []byte {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

type RewrapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ciphertext    []byte                 `protobuf:"bytes,1,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	Context       string                 `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	KeyId         string                 `protobuf:"bytes,3,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewrapRequest) Reset() {
	*x = RewrapRequest{}
	mi := &file_proto_cipher_v1_cipher_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewrapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewrapRequest) ProtoMessage() {}

func (x *RewrapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cipher_v1_cipher_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewrapRequest.ProtoReflect.Descriptor instead.
func (*RewrapRequest) Descriptor() ([]byte, []int) {
	return file_proto_cipher_v1_cipher_proto_rawDescGZIP(), []int{4}
}

func (x *RewrapRequest) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *RewrapRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *RewrapRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

type RewrapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ciphertext    []byte                 `protobuf:"bytes,1,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	KeyId         string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewrapResponse) Reset() {
	*x = RewrapResponse{}
	mi := &file_proto_cipher_v1_cipher_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewrapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewrapResponse) ProtoMessage() {}

func (x *RewrapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cipher_v1_cipher_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewrapResponse.ProtoReflect.Descriptor instead.
func (*RewrapResponse) Descriptor() ([]byte, []int) {
	return file_proto_cipher_v1_cipher_proto_rawDescGZIP(), []int{5}
}

func (x *RewrapResponse) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *RewrapResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

type KeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeysRequest) Reset() {
	*x = KeysRequest{}
	mi := &file_proto_cipher_v1_cipher_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeysRequest) ProtoMessage() {}

func (x *KeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cipher_v1_cipher_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeysRequest.ProtoReflect.Descriptor instead.
func (*KeysRequest) Descriptor() ([]byte, []int) {
	return file_proto_cipher_v1_cipher_proto_rawDescGZIP(), []int{6}
}

type KeysResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key new values are sealed under.
	ActiveKeyId string `protobuf:"bytes,1,opt,name=active_key_id,json=activeKeyId,proto3" json:"active_key_id,omitempty"`
	// Every key that can still decrypt, the active one included.
	KnownKeyIds   []string `protobuf:"bytes,2,rep,name=known_key_ids,json=knownKeyIds,proto3" json:"known_key_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeysResponse) Reset() {
	*x = KeysResponse{}
	mi := &file_proto_cipher_v1_cipher_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeysResponse) ProtoMessage() {}

func (x *KeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cipher_v1_cipher_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeysResponse.ProtoReflect.Descriptor instead.
func (*KeysResponse) Descriptor() ([]byte, []int) {
	return file_proto_cipher_v1_cipher_proto_rawDescGZIP(), []int{7}
}

func (x *KeysResponse) GetActiveKeyId() string {
	if x != nil {
		return x.ActiveKeyId
	}
	return ""
}

func (x *KeysResponse) GetKnownKeyIds() []string {
	if x != nil {
		return x.KnownKeyIds
	}
	return nil
}

var File_proto_cipher_v1_cipher_proto protoreflect.FileDescriptor

const file_proto_cipher_v1_cipher_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/cipher/v1/cipher.proto\x12\tcipher.v1\"H\n" +
	"\x0eEncryptRequest\x12\x1c\n" +
	"\tplaintext\x18\x01 \x01(\fR\tplaintext\x12\x18\n" +
	"\acontext\x18\x02 \x01(\tR\acontext\"H\n" +
	"\x0fEncryptResponse\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x01 \x01(\fR\n" +
	"ciphertext\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\"a\n" +
	"\x0eDecryptRequest\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x01 \x01(\fR\n" +
	"ciphertext\x12\x18\n" +
	"\acontext\x18\x02 \x01(\tR\acontext\x12\x15\n" +
	"\x06key_id\x18\x03 \x01(\tR\x05keyId\"/\n" +
	"\x0fDecryptResponse\x12\x1c\n" +
	"\tplaintext\x18\x01 \x01(\fR\tplaintext\"`\n" +
	"\rRewrapRequest\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x01 \x01(\fR\n" +
	"ciphertext\x12\x18\n" +
	"\acontext\x18\x02 \x01(\tR\acontext\x12\x15\n" +
	"\x06key_id\x18\x03 \x01(\tR\x05keyId\"G\n" +
	"\x0eRewrapResponse\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x01 \x01(\fR\n" +
	"ciphertext\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\"\r\n" +
	"\vKeysRequest\"V\n" +
	"\fKeysResponse\x12\"\n" +
	"\ractive_key_id\x18\x01 \x01(\tR\vactiveKeyId\x12\"\n" +
	"\rknown_key_ids\x18\x02 \x03(\tR\vknownKeyIds2\x8b\x02\n" +
	"\rCipherService\x12@\n" +
	"\aEncrypt\x12\x19.cipher.v1.EncryptRequest\x1a\x1a.cipher.v1.EncryptResponse\x12@\n" +
	"\aDecrypt\x12\x19.cipher.v1.DecryptRequest\x1a\x1a.cipher.v1.DecryptResponse\x12=\n" +
	"\x06Rewrap\x12\x18.cipher.v1.RewrapRequest\x1a\x19.cipher.v1.RewrapResponse\x127\n" +
	"\x04Keys\x12\x16.cipher.v1.KeysRequest\x1a\x17.cipher.v1.KeysResponseB:\n" +
	"\x1ccom.mcpcipher.grpc.cipher.v1P\x01Z\x18mcp-cipher/pkg/pb/cipherb\x06proto3"

var (
	file_proto_cipher_v1_cipher_proto_rawDescOnce sync.Once
	file_proto_cipher_v1_cipher_proto_rawDescData []byte
)

func file_proto_cipher_v1_cipher_proto_rawDescGZIP() []byte {
	file_proto_cipher_v1_cipher_proto_rawDescOnce.Do(func() {
		file_proto_cipher_v1_cipher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cipher_v1_cipher_proto_rawDesc), len(file_proto_cipher_v1_cipher_proto_rawDesc)))
	})
	return file_proto_cipher_v1_cipher_proto_rawDescData
}

var file_proto_cipher_v1_cipher_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_cipher_v1_cipher_proto_goTypes = []any{
	(*EncryptRequest)(nil),  // 0: cipher.v1.EncryptRequest
	(*EncryptResponse)(nil), // 1: cipher.v1.EncryptResponse
	(*DecryptRequest)(nil),  // 2: cipher.v1.DecryptRequest
	(*DecryptResponse)(nil), // 3: cipher.v1.DecryptResponse
	(*RewrapRequest)(nil),   // 4: cipher.v1.RewrapRequest
	(*RewrapResponse)(nil),  // 5: cipher.v1.RewrapResponse
	(*KeysRequest)(nil),     // 6: cipher.v1.KeysRequest
	(*KeysResponse)(nil),    // 7: cipher.v1.KeysResponse
}
var file_proto_cipher_v1_cipher_proto_depIdxs = []int32{
	0, // 0: cipher.v1.CipherService.Encrypt:input_type -> cipher.v1.EncryptRequest
	2, // 1: cipher.v1.CipherService.Decrypt:input_type -> cipher.v1.DecryptRequest
	4, // 2: cipher.v1.CipherService.Rewrap:input_type -> cipher.v1.RewrapRequest
	6, // 3: cipher.v1.CipherService.Keys:input_type -> cipher.v1.KeysRequest
	1, // 4: cipher.v1.CipherService.Encrypt:output_type -> cipher.v1.EncryptResponse
	3, // 5: cipher.v1.CipherService.Decrypt:output_type -> cipher.v1.DecryptResponse
	5, // 6: cipher.v1.CipherService.Rewrap:output_type -> cipher.v1.RewrapResponse
	7, // 7: cipher.v1.CipherService.Keys:output_type -> cipher.v1.KeysResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_cipher_v1_cipher_proto_init() }
func file_proto_cipher_v1_cipher_proto_init() {
	if File_proto_cipher_v1_cipher_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cipher_v1_cipher_proto_rawDesc), len(file_proto_cipher_v1_cipher_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cipher_v1_cipher_proto_goTypes,
		DependencyIndexes: file_proto_cipher_v1_cipher_proto_depIdxs,
		MessageInfos:      file_proto_cipher_v1_cipher_proto_msgTypes,
	}.Build()
	File_proto_cipher_v1_cipher_proto = out.File
	file_proto_cipher_v1_cipher_proto_goTypes = nil
	file_proto_cipher_v1_cipher_proto_depIdxs = nil
}
