// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/cipher/v1/cipher.proto

package cipher

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CipherService_Encrypt_FullMethodName = "/cipher.v1.CipherService/Encrypt"
	CipherService_Decrypt_FullMethodName = "/cipher.v1.CipherService/Decrypt"
	CipherService_Rewrap_FullMethodName  = "/cipher.v1.CipherService/Rewrap"
	CipherService_Keys_FullMethodName    = "/cipher.v1.CipherService/Keys"
)

// CipherServiceClient is the client API for CipherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Encrypts and decrypts the secrets the MCP stack stores.
//
// The point of a separate service is that the keys live in exactly one process. Callers
// hold ciphertext and a key id; none of them can read a value without asking, and none of
// them has to be trusted with a key in order to store one.
type CipherServiceClient interface {
	// Encrypts with the currently active key. The reply names the key that was used, and
	// the caller stores that alongside the ciphertext.
	Encrypt(ctx context.Context, in *EncryptRequest, opts ...grpc.CallOption) (*EncryptResponse, error)
	// Decrypts with the key the ciphertext was sealed under. A key that has been retired
	// for encryption can still decrypt, which is what makes rotation possible without
	// rewriting every stored value at once.
	Decrypt(ctx context.Context, in *DecryptRequest, opts ...grpc.CallOption) (*DecryptResponse, error)
	// Re-seals a value under the active key. Used to migrate stored values off a retired
	// key; the plaintext never leaves this service.
	Rewrap(ctx context.Context, in *RewrapRequest, opts ...grpc.CallOption) (*RewrapResponse, error)
	// Which key new values are sealed under, and which ones can still be opened.
	Keys(ctx context.Context, in *KeysRequest, opts ...grpc.CallOption) (*KeysResponse, error)
}

type cipherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCipherServiceClient(cc grpc.ClientConnInterface) CipherServiceClient {
	return &cipherServiceClient{cc}
}

func (c *cipherServiceClient) Encrypt(ctx context.Context, in *EncryptRequest, opts ...grpc.CallOption) (*EncryptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EncryptResponse)
	err := c.cc.Invoke(ctx, CipherService_Encrypt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cipherServiceClient) Decrypt(ctx context.Context, in *DecryptRequest, opts ...grpc.CallOption) (*DecryptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecryptResponse)
	err := c.cc.Invoke(ctx, CipherService_Decrypt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cipherServiceClient) Rewrap(ctx context.Context, in *RewrapRequest, opts ...grpc.CallOption) (*RewrapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RewrapResponse)
	err := c.cc.Invoke(ctx, CipherService_Rewrap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cipherServiceClient) Keys(ctx context.Context, in *KeysRequest, opts ...grpc.CallOption) (*KeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeysResponse)
	err := c.cc.Invoke(ctx, CipherService_Keys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CipherServiceServer is the server API for CipherService service.
// All implementations must embed UnimplementedCipherServiceServer
// for forward compatibility.
//
// Encrypts and decrypts the secrets the MCP stack stores.
//
// The point of a separate service is that the keys live in exactly one process. Callers
// hold ciphertext and a key id; none of them can read a value without asking, and none of
// them has to be trusted with a key in order to store one.
type CipherServiceServer interface {
	// Encrypts with the currently active key. The reply names the key that was used, and
	// the caller stores that alongside the ciphertext.
	Encrypt(context.Context, *EncryptRequest) (*EncryptResponse, error)
	// Decrypts with the key the ciphertext was sealed under. A key that has been retired
	// for encryption can still decrypt, which is what makes rotation possible without
	// rewriting every stored value at once.
	Decrypt(context.Context, *DecryptRequest) (*DecryptResponse, error)
	// Re-seals a value under the active key. Used to migrate stored values off a retired
	// key; the plaintext never leaves this service.
	Rewrap(context.Context, *RewrapRequest) (*RewrapResponse, error)
	// Which key new values are sealed under, and which ones can still be opened.
	Keys(context.Context, *KeysRequest) (*KeysResponse, error)
	mustEmbedUnimplementedCipherServiceServer()
}

// UnimplementedCipherServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCipherServiceServer struct{}

func (UnimplementedCipherServiceServer) Encrypt(context.Context, *EncryptRequest) (*EncryptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Encrypt not implemented")
}
func (UnimplementedCipherServiceServer) Decrypt(context.Context, *DecryptRequest) (*DecryptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Decrypt not implemented")
}
func (UnimplementedCipherServiceServer) Rewrap(context.Context, *RewrapRequest) (*RewrapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Rewrap not implemented")
}
func (UnimplementedCipherServiceServer) Keys(context.Context, *KeysRequest) (*KeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Keys not implemented")
}
func (UnimplementedCipherServiceServer) mustEmbedUnimplementedCipherServiceServer() {}
func (UnimplementedCipherServiceServer) testEmbeddedByValue()                       {}

// UnsafeCipherServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CipherServiceServer will
// result in compilation errors.
type UnsafeCipherServiceServer interface {
	mustEmbedUnimplementedCipherServiceServer()
}

func RegisterCipherServiceServer(s grpc.ServiceRegistrar, srv CipherServiceServer) {
	// If the following call panics, it indicates UnimplementedCipherServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CipherService_ServiceDesc, srv)
}

func _CipherService_Encrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncryptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CipherServiceServer).Encrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CipherService_Encrypt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CipherServiceServer).Encrypt(ctx, req.(*EncryptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CipherService_Decrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecryptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CipherServiceServer).Decrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CipherService_Decrypt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CipherServiceServer).Decrypt(ctx, req.(*DecryptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CipherService_Rewrap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RewrapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CipherServiceServer).Rewrap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CipherService_Rewrap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CipherServiceServer).Rewrap(ctx, req.(*RewrapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CipherService_Keys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CipherServiceServer).Keys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CipherService_Keys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CipherServiceServer).Keys(ctx, req.(*KeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CipherService_ServiceDesc is the grpc.ServiceDesc for CipherService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CipherService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cipher.v1.CipherService",
	HandlerType: (*CipherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Encrypt",
			Handler:    _CipherService_Encrypt_Handler,
		},
		{
			MethodName: "Decrypt",
			Handler:    _CipherService_Decrypt_Handler,
		},
		{
			MethodName: "Rewrap",
			Handler:    _CipherService_Rewrap_Handler,
		},
		{
			MethodName: "Keys",
			Handler:    _CipherService_Keys_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/cipher/v1/cipher.proto",
}
